using System.ComponentModel;

namespace Mtf.LanguageService.Enums
{
    public enum Country
    {
        Afghanistan,
        Albania,
        Algeria,
        Angola,
        Argentina,
        Austria,
        Australia,
        Bangladesh,
        Belarus,
        Belgium,
        Bolivia,
        [Description("Bosnia and Herzegovina")]
        BosniaAndHerzegovina,
        Brazil,
        Britain,
        Bulgaria,
        Cambodia,
        Cameroon,
        Canada,
        [Description("Central African Republic")]
        CentralAfricanRepublic,
        Chad,
        China,
        Colombia,
        [Description("Costa Rica")]
        CostaRica,
        Croatia,
        [Description("The Czech Republic")]
        TheCzechRepublic,
        [Description("Democratic Republic of the Congo")]
        DemocraticRepublicOfTheCongo,
        Denmark,
        Ecuador,
        Egypt,
        [Description("El Salvador")]
        ElSalvador,
        England,
        Estonia,
        Ethiopia,
        Finland,
        France,
        Germany,
        Ghana,
        Greece,
        Guatemala,
        Holland,
        Honduras,
        Hungary,
        Iceland,
        India,
        Indonesia,
        Iran,
        Iraq,
        Ireland,
        Israel,
        Italy,
        [Description("Ivory Coast")]
        IvoryCoast,
        Jamaica,
        Japan,
        Jordan,
        Kazakhstan,
        Kenya,
        Korea,
        Laos,
        Latvia,
        Libya,
        Lithuania,
        Madagascar,
        Malaysia,
        Mali,
        Mauritania,
        Mexico,
        Morocco,
        Namibia,
        [Description("New Zealand")]
        NewZealand,
        Nicaragua,
        Niger,
        Nigeria,
        Norway,
        Oman,
        Pakistan,
        Panama,
        Paraguay,
        Peru,
        [Description("The Philippines")]
        ThePhilippines,
        Poland,
        Portugal,
        [Description("Republic of the Congo")]
        RepublicOfTheCongo,
        Romania,
        Russia,
        [Description("Saudi Arabia")]
        SaudiArabia,
        Scotland,
        Senegal,
        Serbia,
        Singapore,
        Slovakia,
        Somalia,
        [Description("South Africa")]
        SouthAfrica,
        Spain,
        Sudan,
        Sweden,
        Switzerland,
        Syria,
        Thailand,
        Tunisia,
        Turkey,
        Turkmenistan,
        Ukraine,
        [Description("The United Arab Emirates")]
        TheUnitedArabEmirates,
        [Description("The United States")]
        TheUnitedStates,
        Uruguay,
        Vietnam,
        Wales,
        Zambia,
        Zimbabwe
    }
}